name: LSTM
services:
  lstm:
    image: lstm:latest
    build:
      context: .
      dockerfile: Dockerfile

    container_name: nlp_lstm

    # Enable all GPUs
    gpus: all

    stdin_open: true
    tty: true

    working_dir: /workdir

    volumes:
      # Change this to your local project path
      - .:/workdir

    command: >
      bash -c "
        uv sync &&
        exec bash
      "